### PR TITLE
Feature linux

### PR DESCRIPTION
**Pull request by sandervankasteel**

### CODE REVIEW

**Comment by devinhalladay** [comment]
Looking good from what I can see—you've tested all this and it's working?

**Comment by devinhalladay** [comment]
Looks good 👍🏻 Are you able to find time to write documentation for the readme (just the basics, i.e. do you just run setup-linux.sh? any other setup or knowledge required? etc). Merging! Will edit readme etc for credit later!! You're the man.

**Comment by sandervankasteel** [comment]
Yeah of course, I will write some docs tonight!

**Comment by mjgiarlo** [comment]
I'm going to give what's in `master` a spin later today. Thanks for the Linux support and the great design, y'all!

**Comment by mjgiarlo** [comment]
Worked like a charm! :tada:

**Pull request merged**
