### PR TITLE
Fix playback bar colors

### PR DESCRIPTION
**Pull request by flostellbrink**
Hey, not sure if this is still maintained. Hope it is :smile: 

I just had a go at issue #28 because it bugged me. I did not get the whole Sass thing to work (why are there absolute paths in the css files?) so I just copied the changes to both files.

Hope you consider this an improvement. Thanks!

playbar

### CODE REVIEW

**Comment by sandervankasteel** [comment]
@Owlinated thanks for your pull request, I never got around to finishing this bug 😢 . But I will check your PR in one of the following days.

**Comment by jnylen** [comment]
By the way @sandervankasteel. I pushed it live to the spotio aur package and is running it right now.
Have worked without issues for a week.

**Review by rohmishra — APPROVED** [review]

**Comment by ziazon** [comment]
When is this going to be merged?

**Comment by devinhalladay** [comment]
Done, sorry about that! I didn't even see this until just now.

**Pull request merged**
